name: Make Docs AFter Merging Pull Request

on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python  3.9
        uses: actions/setup-python@v5
        with:
          python-version:  3.9
      - name: Install dependencies
        run: |
          python -m pip install urubu
          python -m pip install markdown==2.6.11
      - name: Running Make
        run: |
          make
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _build/\*.html
          git commit -m "updating _build"
          git push
